apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: eurotunnel-app-run-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo-url
      value: https://github.com/cloud-native-garage-method-cohort/emea-8-eurotunnel-app-thomas-irmer-theo-reignier
    - name: docker-image
      value: quay.io/thomasirmer/eurotunnel-app:$(tasks.clone-source-repo.results.commit)
  pipelineRef:
    name: eurotunnel-app
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi